version: "3.8"
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: "php artisan serve --host=127.0.0.1"
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db
    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: assess_laravel_react
            MYSQL_USER: root        
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: 
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
