version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: assess-db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}                
        ports:
            - 3306:3306
        volumes:          
            - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
     
