version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: assess_laravel_react
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./storage/dbdata:/var/lib/mysql
