version: '3.8'

services:
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV={APP_ENV}
    working_dir: /var/www
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    ports:
      - 3307:3307
    environment:
      - MYSQL_DATABASE=assess_laravel_react
      - MYSQL_USER=root_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: